import { StyleSheet } from 'react-native';
import { spacing, fonts, ThemeColors } from '@/src/theme';

/** Styles shared by the owner/admin Home and the employee Home. */
export type HomeStyles = ReturnType<typeof makeHomeStyles>;
export const makeHomeStyles = (colors: ThemeColors) => StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.surface },
  scroll: { paddingHorizontal: spacing.lg, paddingBottom: spacing.xl },
  edgeToEdge: { marginHorizontal: -spacing.lg, flexGrow: 0 },
  top: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  date: { color: colors.mutedText, fontSize: 13, fontWeight: '600' },
  hi: { color: colors.onSurface, fontSize: 22, fontWeight: '800', letterSpacing: -0.5, fontFamily: fonts.display, marginTop: 1 },
  roundBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.surfaceSecondary, alignItems: 'center', justifyContent: 'center', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border },
  bellDot: { position: 'absolute', top: 9, right: 10, width: 8, height: 8, borderRadius: 4, backgroundColor: colors.onError, borderWidth: 1.5, borderColor: colors.surfaceSecondary },

  ticker: { paddingTop: spacing.sm },
  tk: { flexDirection: 'row', alignItems: 'baseline', gap: 7, backgroundColor: colors.surfaceSecondary, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border },
  tkLabel: { color: colors.brandSecondary, fontSize: 11, fontWeight: '700' },
  tkRate: { color: colors.onSurface, fontSize: 15, fontWeight: '700', fontVariant: ['tabular-nums'] },
  tkChange: { fontSize: 11.5, fontWeight: '600' },
  tkNote: { color: colors.onSurfaceSecondary, fontSize: 12.5, fontWeight: '600' },
  dot: { width: 7, height: 7, borderRadius: 4 },

  money: { marginTop: spacing.md, backgroundColor: colors.surfaceSecondary, borderRadius: 22, borderWidth: 1, borderColor: colors.brandTertiary, paddingHorizontal: 18, paddingVertical: 16 },
  mrow: { flexDirection: 'row', alignItems: 'flex-end' },
  mLbl: { color: colors.onSurfaceSecondary, fontSize: 13 },
  mBig: { color: colors.onSurface, fontSize: 34, fontWeight: '800', letterSpacing: -1, fontVariant: ['tabular-nums'] },
  mRs: { fontSize: 19, color: colors.onSurfaceSecondary, fontWeight: '600' },
  mNet: { fontSize: 13.5, fontWeight: '600', marginTop: 1 },
  chev: { width: 30, height: 30, borderRadius: 15, backgroundColor: colors.surfaceTertiary, alignItems: 'center', justifyContent: 'center' },
  loc: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 11, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider, marginTop: 4 },
  locName: { color: colors.onSurface, fontSize: 14.5 },
  locSub: { color: colors.mutedText, fontSize: 12 },
  locVal: { color: colors.onSurface, fontSize: 15.5, fontWeight: '700', fontVariant: ['tabular-nums'] },
  bar: { height: 4, borderRadius: 2, backgroundColor: colors.surfaceTertiary, marginTop: 6, overflow: 'hidden' },
  barFill: { height: '100%', backgroundColor: colors.brandPrimary },
  inout: { flexDirection: 'row', gap: 10, marginTop: 6 },
  inoutCell: { flex: 1, backgroundColor: colors.surfaceTertiary, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 9 },
  inoutLbl: { color: colors.onSurfaceSecondary, fontSize: 12.5 },
  inoutVal: { fontSize: 16, fontWeight: '700', fontVariant: ['tabular-nums'] },
  mact: { flexDirection: 'row', gap: 8, marginTop: 12 },
  mBtn: { flex: 1, borderRadius: 12, paddingVertical: 11, alignItems: 'center', backgroundColor: colors.surfaceTertiary },
  mBtnGold: { backgroundColor: colors.brandPrimary },
  mBtnText: { color: colors.onSurface, fontSize: 14, fontWeight: '600' },
  mBtnGoldText: { color: colors.onBrandPrimary, fontSize: 14, fontWeight: '700' },

  quick: { paddingHorizontal: spacing.lg, gap: 8, paddingTop: spacing.md },
  q: { width: 78, backgroundColor: colors.surfaceSecondary, borderRadius: 16, paddingTop: 12, paddingBottom: 10, paddingHorizontal: 4, alignItems: 'center', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border },
  qEdit: { backgroundColor: 'transparent', borderStyle: 'dashed', borderColor: colors.borderStrong, borderWidth: 1 },
  qText: { color: colors.onSurfaceSecondary, fontSize: 11, fontWeight: '600', marginTop: 5, textAlign: 'center', lineHeight: 13 },

  sh: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginTop: 26, marginBottom: 10, marginHorizontal: 4 },
  shTitle: { color: colors.onSurface, fontSize: 21, fontWeight: '800', letterSpacing: -0.4, fontFamily: fonts.display },
  shRight: { color: colors.brandSecondary, fontSize: 14, fontWeight: '600' },
  list: { backgroundColor: colors.surfaceSecondary, borderRadius: 18, overflow: 'hidden', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border },
  item: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, paddingVertical: 13 },
  itemSep: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.divider },
  ic: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  mid: { flex: 1, minWidth: 0 },
  t1: { color: colors.onSurface, fontSize: 15, fontWeight: '600' },
  t2: { color: colors.mutedText, fontSize: 12.5, marginTop: 1 },
  act: { backgroundColor: colors.brandTertiary, paddingHorizontal: 11, paddingVertical: 6, borderRadius: 999 },
  actText: { color: colors.brandSecondary, fontSize: 13, fontWeight: '600' },
  amt: { color: colors.onSurface, fontSize: 15, fontWeight: '700', fontVariant: ['tabular-nums'] },
  viewAll: { justifyContent: 'space-between', paddingVertical: 14 },
  viewAllText: { color: colors.brandSecondary, fontSize: 15, fontWeight: '600' },
  day: { color: colors.mutedText, fontSize: 12.5, fontWeight: '700', paddingHorizontal: 14, paddingTop: 12, paddingBottom: 2 },

  staff: { paddingHorizontal: spacing.lg, gap: 10, paddingVertical: 2 },
  p: { width: 64, alignItems: 'center' },
  av: { width: 52, height: 52, borderRadius: 26, borderWidth: 2, backgroundColor: colors.surfaceTertiary, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  avImg: { width: '100%', height: '100%' },
  avText: { color: colors.onSurfaceSecondary, fontWeight: '700', fontSize: 15 },
  pName: { color: colors.onSurfaceSecondary, fontSize: 11.5, marginTop: 5, maxWidth: 64 },
  pIn: { color: colors.mutedText, fontSize: 10.5 },

  owed: { flexDirection: 'row', gap: 8 },
  ow: { flex: 1, backgroundColor: colors.surfaceSecondary, borderRadius: 16, padding: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border },
  owLbl: { color: colors.mutedText, fontSize: 12, fontWeight: '600' },
  owVal: { color: colors.onSurface, fontSize: 17, fontWeight: '800', letterSpacing: -0.3, marginTop: 4, fontVariant: ['tabular-nums'] },
  owSub: { fontSize: 11.5, fontWeight: '600', marginTop: 2 },

  unavail: { color: colors.mutedText, fontSize: 13, marginTop: spacing.lg, marginHorizontal: 4 },
  updating: { color: colors.mutedText, fontSize: 12, textAlign: 'center', marginTop: spacing.lg },
});
